

FROM nginx:latest
RUN apt-get update && apt-get install -y nginx

ENV APP1=/var/www
WORKDIR /usr/share/nginx/htmldockerd


# now there is a folder in dist for angular 6
COPY --from=builder ${APP1}/dist/hellodojofrontend .
COPY proxy.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]



# docker build -t frontend -f Dockerfile  .
# docker run -p 3000:80 -d --name frontend frontend

# to inspect
# docker run -it -p 3000:80  frontend /bin/bash

