AWSTemplateFormatVersion: "2010-09-09"
Description: "A template for creating a deployment pipline applications"

Parameters:
  ApplicationName:
    Type: String
    Description: The application supported by this Pipeline
  DockerBuildFile:
    Type: String
    Description: The DockerFile from the target applciation repo responsible for building/compiling/linting the applciation
    Default: ./Dockerfile-make
  DockerUnitTestFile:
    Type: String
    Description: The DockerFile from the target applciation repo responsible for unittesting the applciation
    Default: ./Dockerfile-unittest
  DockerPackageFile:
    Type: String
    Description: The DockerFile from the target applciation repo responsible for packaging the applciation and uploading to ECR
    Default: ./Dockerfile-package
  TemplateFile:
    Type: String
    Description: The IaC template file located in S3.  Must be preceeded with bucketname/

Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ApplicationName
      RepositoryPolicyText:
        Version: "2008-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload

  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-codebuild-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: awslog
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DeleteLogGroup
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group*"
              - Sid: awss3iactemplatefile
                Effect: Allow
                Action:
                  - s3:Get*
                Resource:
                  - !Sub "arn:aws:s3:::${TemplateFile}"
              - Sid: awss3sourceartifact
                Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:Put*
                  - s3:DeleteObject
                Resource:
                  - !Sub "arn:aws:s3:::${ArtifactBucket}"
                  - !Sub "arn:aws:s3:::${ArtifactBucket}/*"
                  - !Sub "arn:aws:s3:::${SourceBucket}"
                  - !Sub "arn:aws:s3:::${SourceBucket}/*"
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:SetStackPolicy
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:DescribeStacks
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:List*
                  - cloudformation:Describe*
                  - cloudformation:Get*
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}/*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${ApplicationName}"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${ApplicationName}/*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:aws:transform/Serverless-2016-10-31"
              - Sid: awsiam
                Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PassRole
                  - iam:DeleteRolePolicy
                  - iam:PutRolePolicy
                  - iam:GetRolePolicy
                  - iam:CreatePolicy
                Resource:
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/${ApplicationName}*"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:policy/${ApplicationName}*"
              - Sid: cloudwatchevents
                Effect: Allow
                Action:
                  - events:DescribeRule
                  - events:PutRule
                  - events:RemoveTargets
                  - events:PutTargets
                  - events:DeleteRule
                Resource:
                  - !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/*"
              - Sid: awsecr
                Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:CompleteLayerUpload
                  - ecr:DescribeRepositories
                  - ecr:GetAuthorizationToken
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                Resource:
                  - '*'
              - Sid: awsec2
                Effect: Allow
                Action:
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:AttachInternetGateway
                  - ec2:CreateInternetGateway
                  - ec2:DeleteInternetGateway
                  - ec2:DescribeInternetGateways
                  - ec2:DetachInternetGateway
                  - ec2:CreateVpc
                  - ec2:DeleteVpc
                  - ec2:DescribeVpcs
                  - ec2:ModifyVpcAttribute
                  - ec2:DescribeAvailabilityZones
                  - ec2:DescribeAccountAttributes
                  - ec2:DescribeSubnets
                  - ec2:CreateSubnet
                  - ec2:DeleteSubnet
                  - ec2:CreateSecurityGroup
                  - ec2:DeleteSecurityGroup
                  - ec2:DescribeSecurityGroups
                  - ec2:AssociateRouteTable
                  - ec2:CreateRouteTable
                  - ec2:DescribeRouteTables
                  - ec2:DeleteRouteTable
                  - ec2:DisassociateRouteTable
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:ModifySubnetAttribute
                  - ec2:CreateRoute
                  - ec2:DeleteRoute
                  - ec2:allocateAddress
                  - ec2:describeAddresses
                  - ec2:releaseAddress
                  - ec2:CreateNatGateway
                  - ec2:DeleteNatGateway
                  - ec2:DescribeNatGateways
                Resource:
                  - '*'
              - Sid: awselb
                Effect: Allow
                Action:
                  - elasticloadbalancing:CreateLoadBalancer
                  - elasticloadbalancing:DeleteLoadBalancer
                  - elasticloadbalancing:DescribeTargetGroups
                  - elasticloadbalancing:CreateTargetGroup
                  - elasticloadbalancing:DeleteTargetGroup
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:ModifyLoadBalancerAttributes
                  - elasticloadbalancing:CreateListener
                  - elasticloadbalancing:DeleteListener
                  - elasticloadbalancing:DescribeListeners
                  - elasticloadbalancing:CreateRule
                  - elasticloadbalancing:DeleteRule
                  - elasticloadbalancing:DescribeRules
                Resource:
                  - '*'
              - Sid: awsecs
                Effect: Allow
                Action:
                  - ecs:CreateCluster
                  - ecs:DeleteCluster
                  - ecs:DescribeClusters
                  - ecs:RegisterTaskDefinition
                  - ecs:DeregisterTaskDefinition
                  - ecs:CreateService
                  - ecs:DeleteService
                  - ecs:DescribeServices
                  - ecs:UpdateService
                Resource:
                  - '*'

  PipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-codepipeline-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: codepipeline-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource:
                  - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${ApplicationName}-build"
                  - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${ApplicationName}-unittest"
                  - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${ApplicationName}-package"
                  - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${ApplicationName}-deploy"
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:Put*
                Resource:
                  - !Sub "arn:aws:s3:::${ArtifactBucket}"
                  - !Sub "arn:aws:s3:::${ArtifactBucket}/*"
                  - !Sub "arn:aws:s3:::${SourceBucket}"
                  - !Sub "arn:aws:s3:::${SourceBucket}/*"
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PassRole
                  - iam:DeleteRolePolicy
                  - iam:PutRolePolicy
                  - iam:GetRolePolicy
                  - iam:CreatePolicy
                Resource:
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/${AWS::StackName}*"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:policy/${AWS::StackName}*"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/${ApplicationName}*"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:policy/${ApplicationName}*"

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ApplicationName}-build"
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Location: LOCAL
        Modes:
          - LOCAL_DOCKER_LAYER_CACHE
        Type: LOCAL
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: APPLICATION_NAME
            Type: PLAINTEXT
            Value: !Ref ApplicationName
          - Name: DOCKER_FILE
            Type: PLAINTEXT
            Value: !Ref DockerBuildFile
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:

            install:
              runtime-versions:
                docker: 18

            build:
              commands:
                - docker build -f ${DOCKER_FILE}  .
                - echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} > commithash.txt

          artifacts:
            files:
              - '**/*'
          type: zip
      ServiceRole: !GetAtt BuildRole.Arn

  UnitTestProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ApplicationName}-unittest"
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Location: LOCAL
        Modes:
          - LOCAL_DOCKER_LAYER_CACHE
        Type: LOCAL
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: APPLICATION_NAME
            Type: PLAINTEXT
            Value: !Ref ApplicationName
          - Name: DOCKER_FILE
            Type: PLAINTEXT
            Value: !Ref DockerUnitTestFile
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:

            install:
              runtime-versions:
                docker: 18

            build:
              commands:
                - echo "docker build -f ${DOCKER_FILE}  ."

          artifacts:
            files:
              - '**/*'
          type: zip
      ServiceRole: !GetAtt BuildRole.Arn

  PackageProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ApplicationName}-package"
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Location: LOCAL
        Modes:
          - LOCAL_DOCKER_LAYER_CACHE
        Type: LOCAL
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: APPLICATION_NAME
            Type: PLAINTEXT
            Value: !Ref ApplicationName
          - Name: DOCKER_FILE
            Type: PLAINTEXT
            Value: !Ref DockerPackageFile
          - Name: ECR_REPOSITORY
            Type: PLAINTEXT
            Value: !Ref ECR
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:

            install:
              runtime-versions:
                docker: 18

            pre_build:
              commands:
                - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

            build:
              commands:
                - ECR_REPOSITORY_IMAGE_URI=$(aws ecr describe-repositories --query 'repositories[?Name=="${ECR_REPOSITORY}"].repositoryUri' --output text)
                - ECR_IMAGE_VERSION=`cat commithash.txt`
                - docker build -t ${APPLICATION_NAME}:${ECR_IMAGE_VERSION} -f ${DOCKER_FILE} .
                - docker tag ${APPLICATION_NAME}:${ECR_IMAGE_VERSION} ${ECR_REPOSITORY_IMAGE_URI}:${ECR_IMAGE_VERSION}

            post_build:
              commands:
                - docker push ${ECR_REPOSITORY_IMAGE_URI}:${ECR_IMAGE_VERSION}
                - echo "${ECR_REPOSITORY_IMAGE_URI}:${ECR_IMAGE_VERSION}" > ecr_image.txt

          artifacts:
            files:
              - '**/*'
          type: zip
      ServiceRole: !GetAtt BuildRole.Arn

  DeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ApplicationName}-deploy"
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: APPLICATION_NAME
            Type: PLAINTEXT
            Value: !Ref ApplicationName
          - Name: TEMPLATE_FILE
            Type: PLAINTEXT
            Value: !Ref TemplateFile
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: 10
              commands:
                - echo "Downloading ${TEMPLATE_FILE}"
                - aws s3 cp s3://${TEMPLATE_FILE} ./template.yaml

            build:
              commands:
                - ECR_IMAGE=$(cat ecr_image.txt)
                - aws cloudformation deploy --stack-name ${APPLICATION_NAME} --no-fail-on-empty-changeset --template-file ./template.yaml --capabilities CAPABILITY_IAM --parameter-overrides ServiceName=${APPLICATION_NAME} ImageUrl=${ECR_IMAGE}
      ServiceRole: !GetAtt BuildRole.Arn

  ApplicationPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${AWS::StackName}"
      RoleArn: !GetAtt PipelineServiceRole.Arn
      ArtifactStore:
        Location: !Ref ArtifactBucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: SourceCheckout
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: "1"
              Configuration:
                S3Bucket: !Ref SourceBucket
                S3ObjectKey: dist.zip
              OutputArtifacts:
                - Name: SourceCode
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: !Ref ApplicationName
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref BuildProject
              InputArtifacts:
                - Name: SourceCode
              OutputArtifacts:
                - Name: BuildArtifact
        - Name: UnitTest
          Actions:
            - Name: !Ref ApplicationName
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref UnitTestProject
              InputArtifacts:
                - Name: BuildArtifact
              OutputArtifacts:
                - Name: UnitTestArtifact
        - Name: Package
          Actions:
            - Name: !Ref ApplicationName
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref PackageProject
              InputArtifacts:
                - Name: UnitTestArtifact
              OutputArtifacts:
                - Name: PackageArtifact
        - Name: Deploy
          Actions:
            - Name: !Ref ApplicationName
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref DeployProject
              InputArtifacts:
                - Name: PackageArtifact
              OutputArtifacts:
                - Name: DeployArtifact

Outputs:
  RepositoryName:
    Description: The name of the ECR repository housing the docker images for the application
    Value: !Ref ECR
  SourceBucketName:
    Description: The name of the S3 Bucket containing the source code
    Value: !Ref SourceBucket
  ArtifactBucketName:
    Description: The name of the S3 bucket containing the pipeline artifacts
    Value: !Ref ArtifactBucket
